"""
Generates a runnable LangGraph Python file from a GraphBlueprint.
This is the "code artifact" SafeAgent produces — judges can run it directly.
"""
from __future__ import annotations
from models import GraphBlueprint


def generate_langgraph_code(blueprint: GraphBlueprint) -> str:
    agents = blueprint.agents
    edges = blueprint.edges
    entry = blueprint.entry_node

    def node_var(name: str) -> str:
        return name.lower().replace(" ", "_").replace("-", "_")

    def class_name(name: str) -> str:
        return "".join(w.capitalize() for w in name.replace("-", " ").split())

    agent_classes = []
    for a in agents:
        tools_str = ", ".join(f'"{t}"' for t in a.tools)
        cls = f'''\
class {class_name(a.name)}:
    """Role: {a.role}"""

    def __init__(self):
        self.model = ChatAnthropic(model="{a.model}")
        self.system_prompt = """{a.system_prompt[:200].replace('"', "'")}"""

    async def run(self, state: AgentState) -> AgentState:
        messages = [
            SystemMessage(content=self.system_prompt),
            *state["messages"],
        ]
        response = await self.model.ainvoke(messages)
        return {{"messages": [response], "last_agent": "{a.name}"}}
'''
        agent_classes.append(cls)

    # Build graph wiring
    node_inits = "\n    ".join(
        f"{node_var(a.name)} = {class_name(a.name)}()" for a in agents
    )
    node_adds = "\n    ".join(
        f'graph.add_node("{node_var(a.name)}", {node_var(a.name)}.run)' for a in agents
    )

    edge_lines = []
    for e in edges:
        src = node_var(e.from_node)
        dst = node_var(e.to_node) if e.to_node.upper() != "END" else "END"
        if e.condition:
            edge_lines.append(f'    # Conditional: {e.condition}')
            edge_lines.append(f'    graph.add_edge("{src}", {dst})')
        else:
            edge_lines.append(f'    graph.add_edge("{src}", {dst})')
    edges_str = "\n".join(edge_lines) if edge_lines else f'    graph.add_edge("{node_var(entry)}", END)'

    agent_classes_str = "\n\n".join(agent_classes)

    safety_comment = f"""\
# ─────────────────────────────────────────────────────────────────────────────
# SafeAgent Blueprint Export
# Topology : {blueprint.topology_name} (Option {blueprint.topology})
# Agents   : {len(agents)}
# Est. Cost: ${blueprint.prediction.cost_usd:.4f} per run  [PREDICTION]
# Est. Time: {blueprint.prediction.latency_sec:.1f}s  [PREDICTION]
# Generated by SafeAgent — safety-verified via constitutional gate
# ─────────────────────────────────────────────────────────────────────────────
"""

    return f'''\
{safety_comment}
from __future__ import annotations
import asyncio
from typing import Annotated, TypedDict
import operator

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import BaseMessage, SystemMessage
from langgraph.graph import StateGraph, END


# ── Shared state ──────────────────────────────────────────────────────────────

class AgentState(TypedDict):
    messages: Annotated[list[BaseMessage], operator.add]
    session_id: str
    last_agent: str


# ── Agent classes ─────────────────────────────────────────────────────────────

{agent_classes_str}

# ── Graph builder ─────────────────────────────────────────────────────────────

def build_graph():
    graph = StateGraph(AgentState)

    # Instantiate agents
    {node_inits}

    # Register nodes
    {node_adds}

    # Wire edges
    graph.set_entry_point("{node_var(entry)}")
{edges_str}

    return graph.compile()


# ── Entrypoint ────────────────────────────────────────────────────────────────

async def main():
    app = build_graph()
    result = await app.ainvoke({{
        "messages": [],
        "session_id": "local-run",
        "last_agent": "",
    }})
    print("Run complete:", result["last_agent"])


if __name__ == "__main__":
    asyncio.run(main())
'''
